# run: conda env create --file "C:\Users\m1srh\OneDrive - Carl Zeiss AG\Smart_Microscopy_Workshop\python_env\conda_env_ia_czi.yml"
name: imageanalysis_czi
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - conda
  - docutils
  - pip
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - xmltodict
  - lxml
  - openpyxl
  - pydash
  - scikit-image
  - tifffile
  - scipy
  - zarr
  - progressbar2
  - imagecodecs
  - pip:
      - -r file:requirements.txt
# Create an environment
# conda env create --file conda_env_ia_czi.yml

# Update an environment
# conda env update --name imageanalysis_czi --file conda_env_ia_czi.yml --prune

# Remove an environment
# conda remove --name imageanalysis_czi --all

# Show the locations of all versions of Python that are currently in the path
# Windows: where python
# Linux which -a python

