# run: conda env create --file "C:\Users\m1srh\OneDrive - Carl Zeiss AG\Smart_Microscopy_Workshop\python_env\conda_env_czmodel.yml"
name: czmodel
channels:
  - defaults
dependencies:
- python=3.8
- conda
- pip
- jupyter
- matplotlib
- sklearn

- pip:
  - czmodel==1.1.0
  
# Create an environmemt
# conda env create --file "C:\Users\m1srh\OneDrive - Carl Zeiss AG\Smart_Microscopy_Workshop\python_env\conda_env_czmodel.yml"

# Update an environment
# conda env update --name czmodel --file "C:\Users\m1srh\OneDrive - Carl Zeiss AG\Smart_Microscopy_Workshop\python_env\conda_env_czmodel.yml" --prune

# Remove an environment
# conda remove --name czmodel --all

# Show the locations of all versions of Python that are currently in the path
# Windows: where python
# Linux which -a python

